#!/bin/bash

# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Transfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "ubuntu@54.175.223.32":~/

# Check if scp command was successful
if [ $? -eq 0 ]; then
    echo "File successfully transferred to $ubuntu@$54.175.223.32:~/"
else
    echo "Error: Failed to transfer file."
fi
