#!/bin/bash

# Update package list and install nginx with the -y flag
sudo apt-get update
sudo apt-get install -y nginx

# Create a default index.html file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo service nginx restart
