#!/bin/bash
#script configures the nginx server so that /redirect_me is redirecting to another page.
# Check if script is run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root or with sudo."
    exit 1
fi

# Backup the default Nginx configuration file
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

# Define the redirection configuration block
config_block="location /redirect_me {
    return 301 http://www.youtube.com/watch?v=QH2-TGUlwu4;
}"

# Add the redirection configuration block to Nginx configuration
sed -i "/server {/a $config_block" /etc/nginx/nginx.conf

# Test Nginx configuration
nginx -t

# Reload Nginx to apply the changes
service nginx reload

echo "Nginx has been configured for redirection from /redirect_me to http://www.youtube.com/watch?v=QH2-TGUlwu4."
