#!/usr/bin/env bash
# a Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.

pids=$(pgrep -f bash)

# Loop through the PIDs and display the PID and process name
for pid in $pids;
do
	name=$(ps -p "$pid" -o comm=)
	echo "PID: $pid, Process Name: $name"
done
