#!/bin/bash

# Set the desired key file name and passphrase
KEY_NAME="school"
BITS=4096
PASSPHRASE="betty"

# Generate the RSA key pair with passphrase
ssh-keygen -t rsa -b "$BITS" -f "$KEY_NAME" -N "$PASSPHRASE"

echo "RSA key pair created with passphrase 'betty'."
echo "Private key file: $KEY_NAME"
echo "Public key file: $KEY_NAME.pub"
